In [1]:
from typing import Callable, Iterator, List, Union
from osgeo import gdal, gdal_array
import numpy as np
import SharedArray as sa
import skmap_bindings


data = np.zeros((12,5), dtype=np.float32)

data[[8, 6, 3, 2], 0:2] = 200.
data[[0, 1, 3, 5], 0:3] = 200.
data[[0, 1], 4:5] = 200.
indices_matrix = [[0,1,2,3,4],
                  [5,6,7,8,9]]
result_indices = [10, 11]
th = 169.
n_threads = 96
result_scaling = 100.
skmap_bindings.computeBsf(data, n_threads, indices_matrix, result_indices, th, result_scaling)
print(data)

[[200. 200. 200.   0. 200.]
 [200. 200. 200.   0. 200.]
 [200. 200.   0.   0.   0.]
 [200. 200. 200.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [200. 200. 200.   0.   0.]
 [200. 200.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [200. 200.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ 20.  20.  40. 100.  60.]
 [ 40.  40.  80. 100. 100.]]


In [2]:
from typing import Callable, Iterator, List, Union
from osgeo import gdal, gdal_array
import numpy as np
import SharedArray as sa
import skmap_bindings

data = np.zeros((12,5), dtype=np.float32)
reordered_data = np.zeros((3,15), dtype=np.float32)
reordered_transposed_data = np.zeros((15,3), dtype=np.float32)

data[[8, 6, 3, 2], 0:2] = 200.
data[[0, 1, 3, 5], 0:3] = 99.
data[[0, 1], 4:5] = 1.
indices_matrix = [[0,10,2],
                  [5,6,7],
                  [8,0,2]]
n_threads = 96

skmap_bindings.reorderArray(data, n_threads, reordered_data, indices_matrix)
skmap_bindings.reorderTransposeArray(data, n_threads, reordered_transposed_data, indices_matrix)
print(data)
print(reordered_data)
print(reordered_data.transpose())
print(reordered_transposed_data)

[[ 99.  99.  99.   0.   1.]
 [ 99.  99.  99.   0.   1.]
 [200. 200.   0.   0.   0.]
 [ 99.  99.  99.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ 99.  99.  99.   0.   0.]
 [200. 200.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [200. 200.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]]
[[ 99.  99.  99.   0.   1.   0.   0.   0.   0.   0. 200. 200.   0.   0.
    0.]
 [ 99.  99.  99.   0.   0. 200. 200.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [200. 200.   0.   0.   0.  99.  99.  99.   0.   1. 200. 200.   0.   0.
    0.]]
[[ 99.  99. 200.]
 [ 99.  99. 200.]
 [ 99.  99.   0.]
 [  0.   0.   0.]
 [  1.   0.   0.]
 [  0. 200.  99.]
 [  0. 200.  99.]
 [  0.   0.  99.]
 [  0.   0.   0.]
 [  0.   0.   1.]
 [200.   0. 200.]
 [200.   0. 200.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]]
[[ 99.  99. 200.]
 [ 99.  99. 200.]
 [ 99.  99.   0.]
 [  0.   0.   0.]
 [  1.   0.   0.]
 [  0. 200.  99.]
 [  0. 200.  99.]
 [  0.   0.  99.]
 [  0. 