# Fill the shared array with data

In [2]:
import numpy as np
import skmap_bindings
import time

In [3]:
big_size = 200000
small_size = 10000
medium_size = 44721

In [8]:
a = np.ones((big_size,small_size), dtype=np.float32, order='C')
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## Parallel col - big row, small col

In [5]:
test_np = np.ones((big_size,small_size), dtype=np.float32, order='C')
print("Before")
# print(test_np)
start = time.time()
skmap_bindings.parReadFiles(test_np.shape[0], test_np.shape[1], test_np)
print(f"After C++ in {time.time() - start}")
# print(test_np)
test_np[1,1] = 50
print("After Python")
print(test_np)

Before
Hello!
Hello!
After C++ in 9.273570775985718
After Python
[[ 0.  0.  0. ...  0.  0.  0.]
 [42. 50.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


## Parallel col - small row, big col

In [6]:
test_np = np.ones((small_size,big_size), dtype=np.float32, order='C')
print("Before")
# print(test_np)
start = time.time()
skmap_bindings.parReadFiles(test_np.shape[0], test_np.shape[1], test_np)
print(f"After C++ in {time.time() - start}")
# print(test_np)
test_np[1,1] = 50
print("After Python")
print(test_np)

Before
Hello!
Hello!
After C++ in 0.7261636257171631
After Python
[[ 0.  0.  0. ...  0.  0.  0.]
 [42. 50.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


## Parallel col - square

In [7]:
test_np = np.ones((medium_size,medium_size), dtype=np.float32, order='C')
print("Before")
# print(test_np)
start = time.time()
skmap_bindings.parReadFiles(test_np.shape[0], test_np.shape[1], test_np)
print(f"After C++ in {time.time() - start}")
# print(test_np)
test_np[1,1] = 50
print("After Python")
print(test_np)

Before
Hello!
Hello!
After C++ in 7.2585437297821045
After Python
[[ 0.  0.  0. ...  0.  0.  0.]
 [42. 50.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


## Parallel row - big row, small col

In [4]:
test_np = np.ones((big_size,small_size), dtype=np.float32, order='C')
print("Before")
# print(test_np)
start = time.time()
skmap_bindings.parReadFiles(test_np.shape[0], test_np.shape[1], test_np)
print(f"After C++ in {time.time() - start}")
# print(test_np)
test_np[1,1] = 50
print("After Python")
print(test_np)

Before
Hello!
Hello!
After C++ in 0.6263420581817627
After Python
[[ 0.  0.  0. ...  0.  0.  0.]
 [42. 50.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


## Parallel row - small row, big col

In [5]:
test_np = np.ones((small_size,big_size), dtype=np.float32, order='C')
print("Before")
# print(test_np)
start = time.time()
skmap_bindings.parReadFiles(test_np.shape[0], test_np.shape[1], test_np)
print(f"After C++ in {time.time() - start}")
# print(test_np)
test_np[1,1] = 50
print("After Python")
print(test_np)

Before
Hello!
Hello!
After C++ in 0.6090042591094971
After Python
[[ 0.  0.  0. ...  0.  0.  0.]
 [42. 50.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


## Parallel row - square

In [7]:
test_np = np.ones((medium_size,medium_size), dtype=np.float32, order='C')
print("Before")
# print(test_np)
start = time.time()
skmap_bindings.parReadFiles(test_np.shape[0], test_np.shape[1], test_np)
print(f"After C++ in {time.time() - start}")
# print(test_np)
test_np[1,1] = 50
print("After Python")
print(test_np)

Before
Hello!
Hello!
After C++ in 0.6175146102905273
After Python
[[ 0.  0.  0. ...  0.  0.  0.]
 [42. 50.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
